Feature: Add interface for display name
cryptomator/integrations-api pull request #39
Opened 2024-07-01 09:37 UTC by infeo

This PR adds the `NamedServiceProvider` interface to the commons package.

The interface is intended to mark services as "has a printable, human readable name" with the method `getName()`. Alongside with the interface, the annotation `@DisplayName` is added and the default getName() impl checks for this annotation and falls back to the qualified class name otherwise.

Already existing SPIs are not modified, since this would require changes in a lot of different libraries, which should be done in a separate project.

2024-07-04 07:13 UTC, overheadhunter requested changes
Please add a boolean flag denoting whether `value` should be used as a localization key or directly.

Maybe it is even worth replacing `value` by two separate fields `name` and `localizationKey` that are mutually exclusive. Then users of the annotation are forced to explicitly decide for either option. (without `value`, you can't write `@DisplayName("whatDoesThisStringMean?")`)

2024-07-04 16:49 UTC, infeo commented
@overheadhunter I would rather go with an additional, optional parameter than implementing some if/or logic. My goal is for a simple, easy to use annotation, which can be extended if the implementor wants to.

Something like this:
```java
public @interface DisplayName {
	String value();

	/**
	 * Localization key for the display name.
	 * <p>
	 * Optional parameter. If this display is has no localization, it returns an empty string.
	 *
	 * @return
	 */
	String localizationKey() default "";

}
```

The default method in `NamedServiceProvider` then is adjusted to check first for a localizaion key, then the default value and as a last resort the qualified class name.

2024-07-11 14:10 UTC, infeo commented
After a discussion we decided to move the localization to its own interface (see https://github.com/cryptomator/integrations-api/pull/39/commits/750bb022e381619496cac402072f94a50dec9dfa)

2024-07-11 14:13 UTC, overheadhunter commented on src/main/java/org/cryptomator/integrations/common/NamedServiceProvider.java
> +					.getString(localizedDisplayName.key());
if `getString` throws a `MissingResourceException`, fallback to `@DisplayName`?

2024-07-11 14:44 UTC, infeo commented on src/main/java/org/cryptomator/integrations/common/NamedServiceProvider.java
> +					.getString(localizedDisplayName.key());
I changed it in https://github.com/cryptomator/integrations-api/pull/39/commits/def56feafa0c1e91eba0949a9eab71f479a37d16

2024-07-12 06:32 UTC, overheadhunter approved these changes

2024-07-12 11:07 UTC, merged