Widen integrations-api to work with backends that need association
cryptomator/integrations-api pull request #4
Opened 2021-05-29 15:30 UTC by purejava

Part of project [Store Cryptomator vault passwords in KeePassXC](https://github.com/purejava/keepassxc-cryptomator/projects/1)

2021-05-31 06:20 UTC, overheadhunter requested changes

2021-05-31 06:20 UTC, overheadhunter commented on src/main/java/org/cryptomator/integrations/keychain/KeychainAccessProvider.java
> +	 * @return <code>true</code> if associating the KeychainAccessIntegration with the KeychainBackend was successfull.
Can you please refine the JavaDocs and specify what this method is supposed to do? I suspect this is highly KCXC-specific.

2021-05-31 06:20 UTC, overheadhunter commented on README.md
> +- https://github.com/purejava/keepassxc-cryptomator.git
```suggestion
- https://github.com/purejava/keepassxc-cryptomator
```

2021-06-06 05:45 UTC, purejava commented
This PR is probably not needed any more. See this [comment](https://github.com/cryptomator/cryptomator/pull/1668#issuecomment-854404143).

It was discussed and decided that `associate()` and `needsAssociation()` are not necessary. The existing methods in the integrations-apt are sufficient.

2021-06-07 08:02 UTC, closed without merging